services:
  web:
    build:
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn -b 0.0.0.0:8000 ManagmentProject.wsgi:application"

    restart: always
    volumes:
      - ./:/var/www/app
      - media_data:/var/www/app/media
      - static_data:/var/www/app/static
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "8000"

  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/var/www/app/static
      - media_data:/var/www/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  media_data:
  static_data: